language: java
install: true

addons:
  sonarcloud:
    organization: "ekino-1"

jdk:
- openjdk11

env:
  global:
  - GPG_FILE_NAME="ekino-gradle-java-plugin.gpg"
  - ENCRYPTED_GPG_FILE_NAME="ekino-gradle-java-plugin.gpg.enc"
  - PUBLISH_SNAPSHOT_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots/"
  - PUBLISH_RELEASE_REPO_URL="https://oss.sonatype.org/service/local/staging/deploy/maven2/"
  #PUBLISH_REPO_USERNAME
  - secure: e/odz3Llv3QsiPa/3g7oAmkKguy5Zbrp86Oa3XUU2f948uOl1gUdFL+gtE6cfmidvuNe9URCiZwatEmqjI5Azq5vJxdLCB0kb5Rha9MSxFmMd1DT34ijS7Zlxw4iYOF03mnd2i95MZXabcTn4xVvC6vwms0yhPlWnIsD/bLGc/z4VZgn4f9IHxJ/SuwweZoMsjbLzxCdm7nUDmNx5BwoafrVrZJzlRiqfVv+goTH3/ZFSwO3L2bRk8Ax0AuVEfb05807sxY9/03JPwlOZfa+wBwILFbze7h56EexH4RRaTA7e6wfgIHEb693SlZ2Irvqg2b6QdD43S2C62zbOcOM61b2m5s6r+SDq0v8W+zTIczOic4sVSvGz9ZTz+CMgNVOpCNixwwMoHp5bneBNybOVL2k1BtpTDED1toua6jPp/dm0FV7ZDTuaS1FSUHaDAb1pCVFBCTKD1teof5ndW8e4s66qYi37z7uo28slRNrUCWO+lhEN8By/ZQc83kf+zR0Jb+lC1XT0JFw/WdGvsqcueGFm6jC0u/KSe/x1zGrqkZmPm/1C6YKe5rtUtDTpD51e30GjUARAIV5sjX/DOU6A8LkwvrSO1FOO1w2PP5K+IiVyBWf4NDQSE0x3KE8ey4RaIFVfIa2/HE2VGbaB/fW9hvbx3CUwFZTkvm5Xpbo6vQ=
  #PUBLISH_REPO_PASSWORD
  - secure: uQcUaHn+6zMi5HXX0rdf6QnIL00QACL1fslYqFjtIVk02FeqKb3MQxLkTmAW0m1tXBAvgKZ6LmFfDWuY9tZPFrVa03nKpfNLPW/8QeoZRWEK26BHNFG/X31cUZsTyeaNTc8YF7IxDHdyypb7PA4x9jfj1zvufbVEFNQyh4Mz2PX/TqtUA5VYDVODklhigx4XOvxyy2NcytIadvcfGmF9p7OfLxgpABqIncVAoFrJGeLxo57u5d5zghyFnWvpQUTX5qZUo8LOJ2N06mlNUNAZ/jgJl0gXFMmf0eHueInHg3dmLKe/VdLiwVx1SJyDskiLlDmJ+FFHZj7qJ2vQfV0KlmURRInxhekeZtF6keF2A1kJcy+lzkut81oziWicUqaUhsuiXxIPp63K3tEXOKybs/rXwconHQvBptsMReC7t9RfA2NEOkA+IoxtWoWpd6OUt+NR6ulnvmZoFsaF5IEdIonGord1TP+7Hnp8STbfvKnhLJs/6c5+i4TggZhyl54xLnHqVb1vN7Y+eo3Sts1qV95yCrjpZ2LTBFWJeZwE5nwRrAPu7AOHRBHSfKuvjYTgEbzB88VV+kNZJjXwGLr55NdCcI7OzY+wZQy6eYlzxiWLjJ7ycfKVoM/w5IKK5eBTUbw6bKi1SuKEvZ2vL1oYp0yRfkfxWP0G8SvgM/hx72s=
  #GPG_KEY_ID
  - secure: bEcUSu9Aw5b1E6toMTtQ7UW/1q5czbKbOT3eKXKGpVT/ExMBLRYo3OUKAe1TfAewW0ZfNJPVxhsyi8Qb2SvpbwaQEXD/PlGDJF/ulbBt2WreRPglTKem3D6k0l/6OZWLd6QWF/70HklvjWaXHw0TRqi8zUHs2c5c23nRluYWDe/Huwn0mr5TR0vInF7ReQVA0bNOrBcdve+8r0iJ1g0ktkrPVlkY4dg6JphaLxvxq+wbTI7BrxrdpkWxZOD3d8y6EWYIGAH++wQxe429gGKYB236Tou973OQwoLttBgHuioujEy0iEyz0wbZVPfcUAdG8GSd+xWlh4ixKRlk2X+UjW8SkVkeZ7ldQ2hAvsorZmD8+9easS4mbAlixF6NGjbHz9Lt72dMc+9ieQ9ZYKwdrWT8LpDEKEPoPMJKzec5vF2qKc8lfHwC5tr1UbsSnw0i42GHT6TrKLmTOFs47WntUJF96Wx57RdrklW+/SZ44qv49KhwjXXCQjvfs/jtQ+tCPNdznxlVSp1Pd+RuKvilNPbP0eIYwdvVO+idp5cYMQ04RXuojNIm/QgzTXcnqN8yW8/1Qko89HRlFKJbXC4T0qOIhOe2+9pIRgk54QWVvTIayTOCXVLDSo4xi7XEyAbGrd9rFw9nJQDjZWLQi7uf7Q1Y/Dr8SwTCEuRES9sF5ks=
  #GPG_PASSPHRASE
  - secure: o8WK2VM7s4/pPJzAfRboB/WVy83usE4pDWcVyakJppNyf2s/2Ts34lKp9kDymxkwvXzgkfb13uWr8shItx8oaMEV6CQFmB2BtJ2QghDRkgGFuweze2ttON2/YXQMHmLIvlElSyrr8XeZdU5D/WsE9vunmZxEYOQbF6dMShqDVSE/AYL2vlY2KKpUnvMBXbelU40TW9vg/jRQ1ffwvmeL72Hk3KZx1de9WT8b3nqP3Lw0B5O2JEMJO/svmt0PAqGEMRAFme1JMyeiBQ5Ct34zP8hLLkh3YRlldWpFPC9xOi5OfzoXUFEDaRuX6hbDoGNhXfXTBZf/q1QDEz4m6OvxuKKxG32I0m1p4oXI8al8YmuNqPdBZCrNZmaK2CKxfO3AzpOP8imeDArvkNcglGeWEPgWR2CVj6A4GtxeVZFPHdAnUKFjYgRx9PxEpuZT4Olpq0095LeTo7+Il6BDLTMN6ATaaH1w/qZz9vMEVljgyFlUoERrsXeN5Fz4IlNY3ANpcglnDcLp3joWvHsYhF34vbgNvPQ3RR8ryCNZWkgYxfozf/hyJJzGqv1xfV1g/v3RSJNK5Hqcpk0sIjn+OFD9+uSDou8ZSKgNhA4iX89c/sHhdPglVqhsJqzLF1BiBLplqzBNnMYDm0G+kKZaqj83VpuyKKXDcTgWOO58gEvxVVU=
  #SONAR_TOKEN
  - secure: H3wxN0vDRs8sxXuDQmh7cubJ3SS5m/nFvx2YDP2Oqufj10RPLJ8aNh5C795+VYdBv9TCmv/3r5IjnHhYejitdC36kcYW5+vr57V4ZqcX1a+RilSItc75POtPUxCpujv8huko9YXmjq0t5JlapPdP4Ow0ONMmiEZuCDLQXwSetuXkR+BwVFKFGlvEYiqsnnoyq4BSNRJLbwq6xUv7l1mjfB/UVGUW5qwkCs4hi3CTx4u2CGEDIFLhhyiUf8AyxDPJCBlhkMxOWG00a2TCYdvuUccygJutuSrhawnkfS/q601nIJ7mKLeGMDcx7fMpLfUcQwtO3iAb9ZL8J+8289HyrJ5gLy6tbr7tNJZIzkjOpwe20ZJbxNz++ZdFtXn3yx390euLHsisUn+wySnhNmtNfapuGmJ4++aB4HTorxh544YVqklNNpnZO0Gi+kySunExhpgUAf/m3Rabl2gmmKo7paHwPmeCAtHxXId7Yk0f3ltkirkGA5nwFFqQUknkH3v25PmoYwta87tofK5HS04qIvqfUzF8WliuOmfUg491LagvtK4laYiIuh+8wZWRIgeWZN0sbjMHdeoA6TuBB1ukMj9SpJ947HXDSbLnW1mfPCqICJyvTn8jpe4b7ceR+gYLcFtJgQ7y1fC1xO+C52EstCK2TYZ+Nmn9sCfzlqoJeMI=

before_script:
- chmod -R ug+x .travis

jobs:
  include:
  - stage: test
    name: Build
    script: ".travis/build.sh"
  - stage: deploy
    name: Deploy Snapshot
    if: |
      branch = master AND \
      type = push
    script: ".travis/deploy.sh"
  - stage: deploy
    name: Deploy Release
    if: tag IS present AND tag =~ ^(\d)+\.(\d)+(\.(\d)+)*(-[\w]+)*$
    script: ".travis/deploy.sh"
    deploy:
      provider: releases
      api_key:
        secure: PfrSo/Px4svVMLHbY1aNo+f6nWzCRyQ3pb3GLgj85ELfDR3z8NTbYXZ+RxlQKd1wlgecnainz6jl/JI9giXvfLGxiPTsmHVeuS9fgwZhP6hVpAlu4G5/mNDIqShJ7NI4qF73WvKVl4SSgrWNPET02R08nRYCsEhqmzvedH5UGN5npQNHV7wkkOZ610VCwoWLP9XR/c/NMgDiEzW0qFDTBj/XLzucY25TTPhhX3pV+63YsTBW0oAKD/z5InUBN3EWUgJ2pmS1y7IoFE04h15J1GNUReiRbt3ubYDVM5woitrRKiN6hNPQ87lsbMA+m2Nmt1V04PE7jd5WuP3X+f56IzS5az0jr9+KyH3FmpDh4irjeMG08jaTpXVxmYqfdN9rGT155AQ8nK/SSN99aD+Q/NOsF8l0YswpnbuVNt0Ke3QtSHuw+LxqxvUCuKXCkiosCI9qeGrzPZlWZ1qB+TSN/lekcwN+i45VER8t1Ja96mkZPc/YAJTWOA7RedG3csMUg6dle9VYRVGsjMljCLuhOMZ9qDj15/imxUo2pyxBP8GpaA4hzTQg8yCaMt1zzNIFtK8tcXNSzUPoudfIOA2CMaycOFvzR2+CBQ3MwauJhB6lrK6bmvFYUyFWgirk7art9P72GGorxeZOi7gOYQq0Ri2Z3H+hm9jboHbbbQISonE=
      file_glob: true
      file: "$TRAVIS_BUILD_DIR/build/libs/*"
      body: Release of $TRAVIS_TAG
      skip_cleanup: true
      draft: true
      on:
        repo: ekino/gradle-java-plugin
        tags: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
