language: java
install: true
jdk:
- openjdk11
env:
  global:
  - GPG_FILE_NAME="my.travis.gpg"
  - ENCRYPTED_GPG_FILE_NAME="my.travis.gpg.enc"
  - secure: OBEpztuhj8cQzssR5GgdfC6galSZuOAMHC6qgpjKyOepL+8WIRSaUyJnkmmCm4DLaQUAGVYBswRh0GeylYdakIkBdfjRWATTnyl7hgoTTV4DP2pMJ14DOg4FdhRCPKLXEoJjmk23/cKOixxezQtCEUGDJj3D6Q7S9SxvM6xhA7/Qgsnv8ClmkwmqB6R3Aa3uHQ0PSHJnWo1/CB8xW67CSv862QOTyoyHSH3uf+jCZLQifO//UiUf+GwOuyGHiqPjO7aRQJ2LHEIxu2Go1jPnYplKrma3myMgB220FQ7P5b+pPaQr9rsexM3Ksn9XcS1BMAIJ9DX+FJXK9iyYtmsJLz9vU+KaAa9Vz6NQVjKd64tuVd6xzbJ/oXhp9if3Ca9sBG8ZLwPZj4IarI1blYxCwlwh730rFDRER/TTMBDXq4cdtrK7IhAsNhpE0a0zZ00vxsVcSZFNrMJAFvD+L3RcOt9kpMPoZT/Q7Eoz+QF97ZiqzMBBhjskuZ83O6kk0hpudY1PPaOtggKLbICuLgPaOp2HNITy1hsU3QvjZkUSQfNbu4/lBP1Ae30IPeOQ1EtYfOA5nHsWioh9EYwuwpvZSBN2eZdf31+pXTpmiH77+xqbHsQ8dgovzvDxeE/OSsWIxISUr5kGIuyXENrgNghDBzBSE4xEe/lHWKVyy3gJcGo=
  - secure: VRBPxcQl7Tfsd9MuTEMl1Rqd0xDm8BPfzDYkFHIwqoRn0kDy5r5UDILUmqiOcXwt57C92ykxtO4Kfo4Z8kReKjXbNyS+JPsScpiWefdNDDMdv3hoB81h/ZWSnr1NtEyZcMCDr1TVdV0UjOeap74YTqZMZVBI2j8mwph2cKowuDNAjoxZ7v5CocuU+TJYmOVASv/5Iy51HUgxVzDvk22QXbqfzBzcIECDq+YAgJxA5DwBmpzBjzSSC2HMQnJRWnm7cr9NvvFqAs9UDgGmq+iGj7AD95fn6yoDARUUJMm7wa0ZJVDoegUCLF0eHeKGazADHLYFwXPFNSJNdBv1f2DqokRFY5slxqVFyqIIngbtSZReJzncCXmXnoFi0h1E31eS9uJSu7zf6mrbqWvqGpIXgVCXd5epeC3krqmnEOrNfwNCY6rNjWScf6MfIDS6Gkau0ktrJtLtIQJNKUYpX6bPnJvkEkYD6d65uC+kjmOXZc8Eh5noVJoyBGJ7JP+AM4Sd/pm4MWvhVCM5dciOwj40M6DxWcEtBiRTwzeqn8jW4ZIENvGoUOu13wgk94/cU8LMRb/FaXzu8Vr0iaGfvcQpSiruFowyo4Vp9NoogGsHSXVM3rNud+wD2LwaayVB4f7g1GSA1VhLcY8JblW7SeJr+rrHvrmx8yRxsB8mMGY+y9E=
  - secure: e/odz3Llv3QsiPa/3g7oAmkKguy5Zbrp86Oa3XUU2f948uOl1gUdFL+gtE6cfmidvuNe9URCiZwatEmqjI5Azq5vJxdLCB0kb5Rha9MSxFmMd1DT34ijS7Zlxw4iYOF03mnd2i95MZXabcTn4xVvC6vwms0yhPlWnIsD/bLGc/z4VZgn4f9IHxJ/SuwweZoMsjbLzxCdm7nUDmNx5BwoafrVrZJzlRiqfVv+goTH3/ZFSwO3L2bRk8Ax0AuVEfb05807sxY9/03JPwlOZfa+wBwILFbze7h56EexH4RRaTA7e6wfgIHEb693SlZ2Irvqg2b6QdD43S2C62zbOcOM61b2m5s6r+SDq0v8W+zTIczOic4sVSvGz9ZTz+CMgNVOpCNixwwMoHp5bneBNybOVL2k1BtpTDED1toua6jPp/dm0FV7ZDTuaS1FSUHaDAb1pCVFBCTKD1teof5ndW8e4s66qYi37z7uo28slRNrUCWO+lhEN8By/ZQc83kf+zR0Jb+lC1XT0JFw/WdGvsqcueGFm6jC0u/KSe/x1zGrqkZmPm/1C6YKe5rtUtDTpD51e30GjUARAIV5sjX/DOU6A8LkwvrSO1FOO1w2PP5K+IiVyBWf4NDQSE0x3KE8ey4RaIFVfIa2/HE2VGbaB/fW9hvbx3CUwFZTkvm5Xpbo6vQ=
  - secure: uQcUaHn+6zMi5HXX0rdf6QnIL00QACL1fslYqFjtIVk02FeqKb3MQxLkTmAW0m1tXBAvgKZ6LmFfDWuY9tZPFrVa03nKpfNLPW/8QeoZRWEK26BHNFG/X31cUZsTyeaNTc8YF7IxDHdyypb7PA4x9jfj1zvufbVEFNQyh4Mz2PX/TqtUA5VYDVODklhigx4XOvxyy2NcytIadvcfGmF9p7OfLxgpABqIncVAoFrJGeLxo57u5d5zghyFnWvpQUTX5qZUo8LOJ2N06mlNUNAZ/jgJl0gXFMmf0eHueInHg3dmLKe/VdLiwVx1SJyDskiLlDmJ+FFHZj7qJ2vQfV0KlmURRInxhekeZtF6keF2A1kJcy+lzkut81oziWicUqaUhsuiXxIPp63K3tEXOKybs/rXwconHQvBptsMReC7t9RfA2NEOkA+IoxtWoWpd6OUt+NR6ulnvmZoFsaF5IEdIonGord1TP+7Hnp8STbfvKnhLJs/6c5+i4TggZhyl54xLnHqVb1vN7Y+eo3Sts1qV95yCrjpZ2LTBFWJeZwE5nwRrAPu7AOHRBHSfKuvjYTgEbzB88VV+kNZJjXwGLr55NdCcI7OzY+wZQy6eYlzxiWLjJ7ycfKVoM/w5IKK5eBTUbw6bKi1SuKEvZ2vL1oYp0yRfkfxWP0G8SvgM/hx72s=
  - secure: tuJBoBwnb9szWrUMu6cTiUqJTRVAw7GSrWO/N6N/scXB/20NFIqnMDTvzR1Pwi8LBu3pxG0GE/e4AWwhuuTq4k6k4hmHht46YyIiRZZRqRMCjTekfDdyObEqjws5ioswxvYUCWq+eF8P08YXnd0tmckOddFXzATp4AON2+thbHoCVsUZjsAMSwwl9mfde/ITAGUN/5FncGXXyO2X1r0UWuwN49UG44wutNsZgcibE5cciCAaDQ30H4eUtzushK4fTIb4CII/JbdVPOavSQ55NUGKFKhz+rwYrCcgxdYb544iJeeWvpGNYX4ER2YfYNncuyyuQrlU2chR/WAXfKFt7fuNxPLGZbeyPN0e7s69quZHFOXopvcIsBHaW8V9gqK1PdVGVXKo4f1cq1y8mQxD1jUAxrI0rjwlPmgJirdqZqjwU2IZWHeTI+emIDT0Efp/5ellwfPgtDoTMSDlVqKAFVqh0yinWT5hqjQbv9w8izK8k5T3dQWGFf73HvyyEGfRdc7IBC6D/8Rnu9zirIGdGB3+kwjr9sJSBJYSY2KOYJfw6EPS13J07Nh8TRkv58ap3v/L1gA4G/0Yn7PiIAGzEOJE9z8/h8FzxFBdiF3vDcYK9PgbYZ4RUnRTGjo0RLYWorBWbN+FHx+A/jMIap5ryFE0/Hx4LlzYw+c4Nd8X2+M=
  - secure: bVm72cjuIFhxwx/tBjKOevTU5iZtB68L/YTRlSfQRmVKkP1hdW8UOo/tBforzNZch+e9XyeOl+44pE5A5wMQV8nNarqcBc2mlIUyWzSWHJ2zgrY0P8YPlo5q+gu5HFRH0pL2aBje6cPmc8Dif4jZn8ppdevLQFdbeRQqJHozfCv+JXjm6ghvzt4We17hD3ZZrnzbZmImDkqn3Iqtz8TZ2Gr0R3oi+vc0fNzk9mynzFPN/cCECfQUlE4BG+79ZI6+gsoaXGLrQeSHAdQ2RHnr7CMGP52zvPfX0jzXWAXqekPhMPlUGwYXlN6Jpz2CBLXTMmMPYZDM764OLhSxj2/faEQ0sicbsXhYoJP0PCPXrc+u4ugG7OpBUJAmNpZOy4OIfGDqxxV3nyShPRjmujl/NwP60B2JncLXct/zkQ3P8s9UpZgGivcYKCfnrAkCpawLvYtbraYNjMT1xUTdc2/GBiQBtT1sSs22Zu+sCEMTEgdzX21FzuurdeheiOjw7bXqEh3UYwtfMeVxkOaAsAOOIYyfWVEHJ4uwxmEZykXd2E1fngF2QsYPqpnzD/3McXymjnmW9GggTjaayaS3BRIvh7n97VJWeKf0SraRAvLxqM/dFw+1lNkQ6M4NqDUxUEZ0DdLyJJRUhuYo4YQL8NbcM1/UzF7m+KO8PZf3BFuABrE=
before_script:
- chmod -R ug+x .travis
jobs:
  include:
  - stage: test
    name: Build
    script: ".travis/build.sh"
  - stage: deploy
    name: Deploy Snapshot
    if: |
      branch = master AND \
      type = push
    script: ".travis/deploy.sh"
  - stage: deploy
    name: Deploy Release
    if: tag IS present AND tag =~ ^(\d)+\.(\d)+(\.(\d)+)*(-[\w]+)*$
    script: ".travis/deploy.sh"
    deploy:
      provider: releases
      api_key:
        secure: PfrSo/Px4svVMLHbY1aNo+f6nWzCRyQ3pb3GLgj85ELfDR3z8NTbYXZ+RxlQKd1wlgecnainz6jl/JI9giXvfLGxiPTsmHVeuS9fgwZhP6hVpAlu4G5/mNDIqShJ7NI4qF73WvKVl4SSgrWNPET02R08nRYCsEhqmzvedH5UGN5npQNHV7wkkOZ610VCwoWLP9XR/c/NMgDiEzW0qFDTBj/XLzucY25TTPhhX3pV+63YsTBW0oAKD/z5InUBN3EWUgJ2pmS1y7IoFE04h15J1GNUReiRbt3ubYDVM5woitrRKiN6hNPQ87lsbMA+m2Nmt1V04PE7jd5WuP3X+f56IzS5az0jr9+KyH3FmpDh4irjeMG08jaTpXVxmYqfdN9rGT155AQ8nK/SSN99aD+Q/NOsF8l0YswpnbuVNt0Ke3QtSHuw+LxqxvUCuKXCkiosCI9qeGrzPZlWZ1qB+TSN/lekcwN+i45VER8t1Ja96mkZPc/YAJTWOA7RedG3csMUg6dle9VYRVGsjMljCLuhOMZ9qDj15/imxUo2pyxBP8GpaA4hzTQg8yCaMt1zzNIFtK8tcXNSzUPoudfIOA2CMaycOFvzR2+CBQ3MwauJhB6lrK6bmvFYUyFWgirk7art9P72GGorxeZOi7gOYQq0Ri2Z3H+hm9jboHbbbQISonE=
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/build/libs/*"
    body: Release of $TRAVIS_TAG
    skip_cleanup: true
    draft: true
    on:
      repo: ekino/gradle-java-plugin
      tags: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
