language: java
install: true
jdk:
- openjdk11
before_install:
- chmod -R ug+x .travis
- ".travis/install.sh"
script:
- chmod -R ug+x .travis
- ".travis/build.sh"
- ".travis/deploy.sh"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: eqgd+Ea8fMe1nN/MeEZK05Mv0IyoaNl7XVOE/D9S3EfwPKdzE6mVl05+HoFeC7swme/DDUcfv9VdE2Y+hFZkdMlDjZ+Zoeo51ZGHiweDqr7GcYSqYJht/8GxJN9LSyAdlFuMhDB9duwzTsW6ozQfgoNIqiCz2Zf6kWp2iiVk07MFgXsS2XR/hnI35iSbbUjLJJhgAHmz3M0xRhFh71Z0UlAbGx6LGTF3FjWihW/MRLPwvv9kg3IaCSzpujXa1UAsXJwYqERXbUnyxMOzITw1rJIP4VCxBiR4Cucrw/BFclj/J3BQnNB1oM1pjumQrU1ZFeKBOz4DepndfvCrgGJvLsCAX6PXSFqd2BSVWO1B6Qy0qSDxvxrTr55rtH9cRQzU3jEdtnNTFw+opOwAWYNbSHD0Srx6EOBA2RBLZYhqupJVUnmHXFXt5vXPhWsomvNQ9514VhE/t2JDq6KTRLLoSut4bQJZDaRIaLL5ZlV3diQ53+sZaUnrrb474dsR71K6Z3U4zpY3POCs9OjCbhQs7AxEStsTMRDyK43kOpcAEwtVtxFbOOpzSKf3K51U+N1Wbc/rEliM/DlHRLmtSKW2U1/FGvyJ+3bY5FnCh0bWn5+vVKdoFbWc6vNZvvm+jgQsEnVFZjyoviwfVX7sb3T7MOtFw9x+dNGbcxlxdm6B+Kk=
  - secure: L/y593KYgM0t+dMUTvtcvjzQLEhVA61atyLANY49vHNXxQC45GCdNq9gMfTIbGqs1c/sGWCReS9xw/grXJ48sqBblM5QvNNwJOCAiA2guPMW10WmZqkypLOnA6aP7nPqFFVs8uLBP81pjuyF7s9swYe7vSCOAEGy4RN7YGwOdH7R0ovIWsv/WYRZblC+ecs4FGyIuX0GNF0Yd6vmRLpFg3BHoK93uPi+rG3dusUey0bPoHwUIuGVq19uN3DWOwm65wo4iVnEhatou9gjq9OSNSwYgLR53E1YWWbXHRX3RIAIymWC4OFDQeliYZIJscMIrWP6l6rfjj9GudEhYwgZrSIoupCbbsEZSmid3v/kergClTMZr+slUHlQNEKkJMH9Bs1I/L0RBG+PNFbwX3m4BxhkVNcxGLQf9QqeNkgwhmp0+H/bQ/5LiCeP0h4NGs9RY9IORHkEtkr2QPKpshA6BW+6QzwQubwkeZH982RbisDfE05/qoy8GN/o/fRrDU/8mplf2h2/X6dtKGcQAO1cyN2D1CPLUAEH6VX18QNQVxBfdgnCXb91k3vV06IP+Ga+3XHZVPDf+TUiPIKgHcEwrGzLIemoUX9GBPRHxiRl1vdegm5gvDD0mI93MiBvKw0gZ6MPy50rXAX9G1CjeSTX9OB/vg5Yfmb4X6f3Lwjhg+4=
  - secure: p/bX3s0C4G7+NUYF/NnUymAbppu0wDrh0oqZxe7gx97KYvR1zrW7bWfSG3DI/Fm5w/OaV1eZ5MVPuh243bVsHBbHOBjvEhqMI30S56lDZgSzlNd3JcFTiAPZHWYSpZ5+OYbon312RmG9PKZpHAlxlquBGpZPej+BMlJdHbAGrjvhe+fpTaPlXfNSUDGDgFGKizf2bMeWeVatCMwR8pG2o0j1TXUTOWoBHD8h/suT/5X1d9UOHkcbmPjvCNh5gKCSpplCbU7eVaRW2HROe9/yJ3HlRGjohgaVT2tNZYgkUQjvE4RvLn+RxqTZYro8pS5ic//Oc0HUbLpBkVEAoT/Ev1bEpJxNKdKltVdck6q5XejfO96hdDoHbjlrTVK5QhY5r6I0Wcb+DgHTNGTq0dQAhtZbvNYuy1HIH2NHw+NKa3Q4VOuOW2YXKEvqayN/aZ6hLdXGtdjHzyasQBixyn/IW1LOUbUGY/OnG/vvoPkpckeKpucoVGPHv4zLKAKs4pHH8E0sp9kzqR2zsfiqPoSSPa3o0JM8zukBgMArqwO9Q9fIO7a1BgHSvbPuoqtBGnQay1GXY3F9KXAM8KuP4BMAKAWAXkuiepGa1c+PlZoSrAk+/SmJ28seY8i2eGfc9vgI33l/dhK30Jbtjj3steDITQw9rwDMTPTlQCxkpMe46wo=
  - secure: TdWFDBC3guAXKzMTH22e7kGKA1SvCB4Kqu8yugy+bEW5nYsaKiUZVMKVMhwFaLBsf3E9uS9fV9Eg1qKqtpjoFAKkY/JAoRJM0nx3HQGJ0BND4BKhcaTBHXxW7A7eSqFLL3L4JDTW3aL4Kjxh7S78/9w7Jm0KiSivPCPzmxX7T6r1Mwn4rdjhAsWS03N/xJ/ElIoOrxjwZ519ZWE/1h7XIqbrV90ffFVK1AzxiZmp+ekAjIhrENzQdNn4p7xJ1lhwMs7OyedyMITlrrVl4ldeIIkOIDvL1KVoAXxs0udTUbR0dt/3TtaAqEwhEU1f5Ugb8RwiHumHHfbobja2FcVqPvNOAs5k0WhCwansz+h3nOB/DzgcxHyk/0HZz9yzCmrg1s0ce0ljvv0iHPTEyX3p3tEjbOGwlOUuEie4jxEKwqe6v7jiLrvevdADUDGkTmQ2AKQT/O1TsFqv9FB5rUOoDSrq0lmlbqNHBaBkRCd2Ac4Q4TTU+78dp7VKKJpZTRLXRLNfe18MXp3BI2Inchq9JyVyFZiy9I7p18R32bgneGSIfxyck5NP2XRUYYR61a+r8Y2J1kfFafr1VxSCPei36X45wdVVlDNDmqpXWVDyOYwBFltuMaakBqy8CNheWLsScGYMFt3Sz/1H9sOWnlSV/7ab1IpWNHIZBcFuTll0BRU=
deploy:
  provider: releases
  api_key:
    secure: caq/pYD0the0BeiD/0mjcxnw8Wy6t7WH19ft/zpCUDYLjIfiKCXPPeBx3f4ZmKUKahjgks6o1Aktw20T9qCNgRI90+5kM7IIe5iUiMTQnm5RL+WfdN0qu4ZZXgIgJdgsf05iTw5yiUel7h+ZdYT8c3OkcKi7dlNAMpRi5wJ/oesaSYT7zllU9tSa/rKWVqtYXz1RY82+FJajYvzJL5xeaBbQhKQ/khZYiZitPFvmcUHXT4Vi/NYtAS9ul0g12lJBu1BXQexTDvw7QuVJhhGySCzS5Cw5iaOwVDfXS+DUp0Z8RqpfmooUwzulXKhErqTyPuoKTIQLw2k9w40XvSZmGIhTf+hJKHem9aUuiOxD1VZBbFOgOvkJqTFFXp+vgzGbHb2yVRJAUeZTOsFAvA7js4iADf571URd1axPca54gwCw1FsMzozHCg5wTtzD2fUMYN/yDTJJ0syY3Firuz8XPnDHrx7TX9ULT63O3UruND0zBpGWU+xy2zWb8NL8WapYFzV0zB7i71JFCNFiwygRmtSAs6M2821ybBn8Y9w7UMN5QudJ4ZbQPR6Y0P21rj5Ks7D/t8Qtkqws2wMFD1Y0wIcnBP+PWBXWiKl1vAIvgnwixdznhTQLaTEnO2HbFIK2Q7P4OAnPpDhx4DFNBcR0FOzD1M8O1IkZyFuKkyK3tmA=
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/build/distributions/*"
  skip_cleanup: true
  on:
    repo: ekino/gradle-java-plugin
    tags: true
after_deploy:
  - .travis/release.sh
