language: java
install: true
jdk:
- openjdk11
env:
  global:
  - GPG_FILE_NAME="my.travis.gpg"
  - ENCRYPTED_GPG_FILE_NAME="my.travis.gpg.enc"
  - secure: AiPWQfISo0iWnpCMWVSZ/S+HeLsEvjQ6m0yIMzDZJ7mSgGLZOuqLYEeefUEkVRsFT2FEwBLmMMeGOx3GK6dhLhJ9rj+EMlTBsOmYoO9fj6QnsJfPfbWRuDVI5L66dlj4zyMMtESM0ekYbPSD14of564fVPXMv73kswZu8GGiEDd7ZGhx/Plrb9bKD/eYKa9ynb6oalaYNjbiUVuevhZtVrfbKIuvBku2jgf7G9bp1uJfB0oz50Fz2kbuPn2rI2lR/1JYd3J9io5Gm6Dvdz0mGLYsyo5Jp/Rhke4mCkcwdi5YdSP1hGFLrL1es8GqfQRVxm+8QZRz12Lt6V8hMUWOd1ESin7e3FKm7zM+tp423tooDFrN2YDZfoKi1MgbHZzYnS29+DNjNO+rVBFoxJ6Q2NLwZ+r0JwUcMB1CIrwsqfphA4i7pPDlTaEU1PJDUWMQIqHxysTqVF+jLUjboOa9JPUU7auWNdxS4TS5g5MGG26X2dD27Tb1sHaPO+X1o0RjtuzUi1S1Ab51KJO2CyzTnGVlWDEKpc5P8aKmtMUUuNeBZbh4x4Gf15SSM5kul8ajp7ueNc5I3rj/ozlngm1oEOqpLm3AYDeui9EVRNxS17CrWGhV35N8wA/DgZCLBEZfSyzFR8qrw3MR2rUcsPYC7eQy3zGLO89ymRCNMMJxV6Q=
  - secure: TQMmN4vXoMB18dMgH1yZcxx2rmSJ317q16QS6fQ8zb8wTISYPsiY1iSdfUMhEcRepFWvghUfZ6Y/Udl0vYefhEw6+VXFBE4tBIa739ykN6BZBLtkNMT9CgDMpE4RB2juRN/UNZSBx7RS07BKEbhdQWPZ4tMolUoTCUZ6xMHbnXGCkZ25RnDk3q570Ikc+zgXxydWEojLMqk5w0ApKey8jAxfkuxyYAbKvaaQOmG7peyl0q70zvCW7nC8ZJIUAiymvb4vTwpgOg/MruAqbL5SxvfPrvQBMHr/J/W+fRhLtJFehFSXU6DJq3jQTbUs3MxgLq0b4MWtV+WAilmKvjexqTCrz3u9DCoVOg0aRJaeRVnPZYU3eV9Nnks2kpCbzRdhk6AW+1vzS44RKazAiueMfwq1cplQ969x3s7Rn0WWC15FpLq+usbMCRg9zXAa4zdUmTUPcNepBopnPKdRaiOGMo+hxgzhZQPso7JeC+4IHyNb1TUom4MDcNt6jY2CocjZoG5dbAxiDTZZppF52JGqRlRKT69DyG4lEYEA3A/qCazI1LFLvRorE8YdYGCv5JfIcJUH0dYEGKuEw3Om7kgPKG2hkblsyjdx3Ku1FxE8L22DP25ipMpb07GmC2DzM6xiIe32ru2VpZ5H9hS3HXZxPW51pkeeaJXNIXDeuC2jgM4=
  #PUBLISH_SNAPSHOT_REPO_URL
  - secure: OBEpztuhj8cQzssR5GgdfC6galSZuOAMHC6qgpjKyOepL+8WIRSaUyJnkmmCm4DLaQUAGVYBswRh0GeylYdakIkBdfjRWATTnyl7hgoTTV4DP2pMJ14DOg4FdhRCPKLXEoJjmk23/cKOixxezQtCEUGDJj3D6Q7S9SxvM6xhA7/Qgsnv8ClmkwmqB6R3Aa3uHQ0PSHJnWo1/CB8xW67CSv862QOTyoyHSH3uf+jCZLQifO//UiUf+GwOuyGHiqPjO7aRQJ2LHEIxu2Go1jPnYplKrma3myMgB220FQ7P5b+pPaQr9rsexM3Ksn9XcS1BMAIJ9DX+FJXK9iyYtmsJLz9vU+KaAa9Vz6NQVjKd64tuVd6xzbJ/oXhp9if3Ca9sBG8ZLwPZj4IarI1blYxCwlwh730rFDRER/TTMBDXq4cdtrK7IhAsNhpE0a0zZ00vxsVcSZFNrMJAFvD+L3RcOt9kpMPoZT/Q7Eoz+QF97ZiqzMBBhjskuZ83O6kk0hpudY1PPaOtggKLbICuLgPaOp2HNITy1hsU3QvjZkUSQfNbu4/lBP1Ae30IPeOQ1EtYfOA5nHsWioh9EYwuwpvZSBN2eZdf31+pXTpmiH77+xqbHsQ8dgovzvDxeE/OSsWIxISUr5kGIuyXENrgNghDBzBSE4xEe/lHWKVyy3gJcGo=
  #PUBLISH_RELEASE_REPO_URL
  - secure: fhtKsI/PiuRxb+QDJKRC7G1k6qQwhMuOf4M2TQ/rBTUiY3x9lbKdp9kvDkh+u+GdLRJbkGwMllfh89tJCWziVLFj/qprf+wO+25rQBT1zIwRIwI1McaTrtMqBFnEC7DlT8JMvcqijGIsilA0O1VkRMwojjA+7welfT81eYjLrjMAKMk76pq/80wxKZ8n4ZZ/NPgIXsmofu53CDrdXKsWk2kTosVEjU+wa39z9CNqp04RQiJRjJRwUyTvJ/0CfJOunvXokijnNEowKJz8spPc39y7g9RwHfG3JLi7hniiiXt7TG2BjiZTp3K5qrGLD/yjoZ8ruA+dUkhWuYWJe5+vZ7YXvqMNFLQwcFzezaSsY9u3zmPc4l+4fK5ehqSqNXx7RSKeqnmvlLJMKPkoPpJaGWqpHmLFgf4PiiIQ8jbdLb4Xaeik2a0lTftDQaXOXtxDJaAqTlCWluRNaGxwKNDv9tgIOFfDeUedOYAve9stbeqFFve4jKmbg/6KuH1Z2nVB9n1j2b+f9fws4T/NQafZWpfeA7idYHZVAaKbF6jeiyG0Z1JFxTpUhr4lyC3t1ynosjPdbkPN1zJBIbGxYBKCChdTBp557tq5FAvVVsz9nyIUrhT0SB4GTFYkQiJWcaHuW74OH0CTYtcFbFrdF+HL+lVblhC+YQ2AJrJrwgzkcw0=
  #PUBLISH_REPO_USERNAME
  - secure: e/odz3Llv3QsiPa/3g7oAmkKguy5Zbrp86Oa3XUU2f948uOl1gUdFL+gtE6cfmidvuNe9URCiZwatEmqjI5Azq5vJxdLCB0kb5Rha9MSxFmMd1DT34ijS7Zlxw4iYOF03mnd2i95MZXabcTn4xVvC6vwms0yhPlWnIsD/bLGc/z4VZgn4f9IHxJ/SuwweZoMsjbLzxCdm7nUDmNx5BwoafrVrZJzlRiqfVv+goTH3/ZFSwO3L2bRk8Ax0AuVEfb05807sxY9/03JPwlOZfa+wBwILFbze7h56EexH4RRaTA7e6wfgIHEb693SlZ2Irvqg2b6QdD43S2C62zbOcOM61b2m5s6r+SDq0v8W+zTIczOic4sVSvGz9ZTz+CMgNVOpCNixwwMoHp5bneBNybOVL2k1BtpTDED1toua6jPp/dm0FV7ZDTuaS1FSUHaDAb1pCVFBCTKD1teof5ndW8e4s66qYi37z7uo28slRNrUCWO+lhEN8By/ZQc83kf+zR0Jb+lC1XT0JFw/WdGvsqcueGFm6jC0u/KSe/x1zGrqkZmPm/1C6YKe5rtUtDTpD51e30GjUARAIV5sjX/DOU6A8LkwvrSO1FOO1w2PP5K+IiVyBWf4NDQSE0x3KE8ey4RaIFVfIa2/HE2VGbaB/fW9hvbx3CUwFZTkvm5Xpbo6vQ=
  #PUBLISH_REPO_PASSWORD
  - secure: uQcUaHn+6zMi5HXX0rdf6QnIL00QACL1fslYqFjtIVk02FeqKb3MQxLkTmAW0m1tXBAvgKZ6LmFfDWuY9tZPFrVa03nKpfNLPW/8QeoZRWEK26BHNFG/X31cUZsTyeaNTc8YF7IxDHdyypb7PA4x9jfj1zvufbVEFNQyh4Mz2PX/TqtUA5VYDVODklhigx4XOvxyy2NcytIadvcfGmF9p7OfLxgpABqIncVAoFrJGeLxo57u5d5zghyFnWvpQUTX5qZUo8LOJ2N06mlNUNAZ/jgJl0gXFMmf0eHueInHg3dmLKe/VdLiwVx1SJyDskiLlDmJ+FFHZj7qJ2vQfV0KlmURRInxhekeZtF6keF2A1kJcy+lzkut81oziWicUqaUhsuiXxIPp63K3tEXOKybs/rXwconHQvBptsMReC7t9RfA2NEOkA+IoxtWoWpd6OUt+NR6ulnvmZoFsaF5IEdIonGord1TP+7Hnp8STbfvKnhLJs/6c5+i4TggZhyl54xLnHqVb1vN7Y+eo3Sts1qV95yCrjpZ2LTBFWJeZwE5nwRrAPu7AOHRBHSfKuvjYTgEbzB88VV+kNZJjXwGLr55NdCcI7OzY+wZQy6eYlzxiWLjJ7ycfKVoM/w5IKK5eBTUbw6bKi1SuKEvZ2vL1oYp0yRfkfxWP0G8SvgM/hx72s=
before_script:
- chmod -R ug+x .travis
jobs:
  include:
  - stage: test
    name: Build
    script: ".travis/build.sh"
  - stage: deploy
    name: Deploy Snapshot
    if: |
      branch = master AND \
      type = push
    script: ".travis/deploy.sh"
  - stage: deploy
    name: Deploy Release
    if: tag IS present AND tag =~ ^(\d)+\.(\d)+(\.(\d)+)*(-[\w]+)*$
    script: ".travis/deploy.sh"
    deploy:
      provider: releases
      api_key:
        secure: caq/pYD0the0BeiD/0mjcxnw8Wy6t7WH19ft/zpCUDYLjIfiKCXPPeBx3f4ZmKUKahjgks6o1Aktw20T9qCNgRI90+5kM7IIe5iUiMTQnm5RL+WfdN0qu4ZZXgIgJdgsf05iTw5yiUel7h+ZdYT8c3OkcKi7dlNAMpRi5wJ/oesaSYT7zllU9tSa/rKWVqtYXz1RY82+FJajYvzJL5xeaBbQhKQ/khZYiZitPFvmcUHXT4Vi/NYtAS9ul0g12lJBu1BXQexTDvw7QuVJhhGySCzS5Cw5iaOwVDfXS+DUp0Z8RqpfmooUwzulXKhErqTyPuoKTIQLw2k9w40XvSZmGIhTf+hJKHem9aUuiOxD1VZBbFOgOvkJqTFFXp+vgzGbHb2yVRJAUeZTOsFAvA7js4iADf571URd1axPca54gwCw1FsMzozHCg5wTtzD2fUMYN/yDTJJ0syY3Firuz8XPnDHrx7TX9ULT63O3UruND0zBpGWU+xy2zWb8NL8WapYFzV0zB7i71JFCNFiwygRmtSAs6M2821ybBn8Y9w7UMN5QudJ4ZbQPR6Y0P21rj5Ks7D/t8Qtkqws2wMFD1Y0wIcnBP+PWBXWiKl1vAIvgnwixdznhTQLaTEnO2HbFIK2Q7P4OAnPpDhx4DFNBcR0FOzD1M8O1IkZyFuKkyK3tmA=
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/build/libs/*"
    body: Release of $TRAVIS_TAG
    skip_cleanup: true
    draft: false
    on:
      repo: ekino/gradle-java-plugin
      tags: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
